# Default values for sericy-visu-one-template-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service_type: ui
service_name: sericy-om-test-shell-ui

resources:
   limits:
     memory: 15Mi
   requests:
     cpu: 3m
     memory: 10Mi
